config/routes.rb
Jpt::Application.routes.draw do

  resources :shainmasters, only: [:index] do
    
  end
  
  resources :shozokumasters, only: [:index] do
    
  end
  resources :joutaimasters, only: [:index] do
    
  end
resources :bashomasters, only: [:index] do
    
  end

  # get 'events/index'

  get 'joutaimasters/index'

  get 'bashomaster/index'

  resources :events, only: [:index, :new, :create, :edit, :update] do
		collection do
			post :change_user
			post :ajax
		end
	end
	
  resources :kouteimasters do
    collection do
      post :ajax
    end
  end

  # get "shozais/index"
  post "shozais/select"
	resources :shozais do
		collection do
			# post :getAjax
			get :main
		end
	end

	root to: 'users#login'

	# post 'users/login'

	# match 'login', to: 'users#create', via: [:post]
	# match 'change_pass', to: 'users#change_pass', via: [:get,:post]
	# match 'change_pass_exc', to: 'users#change_pass_exc', via: [:get,:post]

	match 'main', to: 'main#index', via: [:get]

	match 'tree', to: 'tree#index', via: [:get]
	match 'call_by_ajax', to: 'tree#getAjax', via: [:post]
	match 'uploadFile', to: 'tree#upload', via: [:get,:post]
	match 'email', to: 'tree#email', via: [:get,:post]
	match 'emailxhr', to: 'tree#emailxhr', via: [:post]
	match 'scroll', to: 'tree#scroll', via: [:get,:post]

	# match 'multiselect', to: 'tree#multiselect', via: [:get,:post]
	# match 'employer', to: 'tree#employer', via: [:get,:post]

	# resources :employers, only: [:index, :create, :new, :edit, :show, :update, :destroy]
  resources :users, only: [:create, :new] do
    collection do
      get :login
    end
  end
  resources :employers

end

app/models/event.rb
class Event < ActiveRecord::Base
  self.table_name = 'events'
  validates :開始, presence: true
  validates :状態コード, presence: true
  validates :場所コード, presence: true
  validates :工程コード, presence: true

  def self.binding_event_by_change_user(user_id)
    sql = "SELECT a.*, b.場所名, c.状態名, d.工程名"
    sql << " FROM events a LEFT OUTER JOIN 場所マスタ b ON a.場所コード = b.場所コード"
    sql << " LEFT OUTER JOIN 状態マスタ c on a.状態コード = c.状態コード"
    sql << " LEFT OUTER JOIN 工程マスタ d on a.所属コード = d.所属コード and a.工程コード = d.工程コード"
    sql << " WHERE a.社員番号 = '#{user_id}'"
    @events = Event.find_by_sql(sql) 
    # @events.each do |event|
    #   if event.終了.nil?
    #     event.終了 = Date.tomorrow.to_s
    #   end
    # end
    # return @events
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [ :show, :edit, :update, :destroy]
  before_action :set_param, only: [ :create, :new, :show, :edit, :update, :destroy]
  before_action :init, only: [ :create, :new, :edit, :update]

  helper EventsHelper
  
  def index
    # @events = Event.all
    @events = Event.binding_event_by_change_user(session['selected_user'])
    # @user = User.all
    @shains = Shainmaster.all
  end
  
  def edit
    init
  end
  
  def new
    @event = Event.new
    @hash_param = { basho_name: '', koutei_name: '', joutai_name: '' }
    init
  end
  
  def create
    @event = Event.new(event_params)
    # Check param before submit
    
    params_valid
    
    if @errors.any?
      respond_to do |format|
        init_hash_name
        format.html {render action: 'new'}
      end
      return
    end
    
    respond_to do |format|
      if @event.save
        Rails.logger.info 'Event created'
        format.html { redirect_to events_url, notice: '新規成功作成出来ました。' }
      else
        Rails.logger.info 'Event uncreated'
        @hash_param = { basho_name: '', koutei_name: '', joutai_name: '' }
        format.html { render 'new' }
        # format.html { redirect_to new_event_url }
        format.json { render json: @event.errors, status: :unprocessable_entity }
        # format.json { render json: @user.errors, status: :unprocessable_entity }
        # format.js { render json: @user.errors, status: :unprocessable_entity }
        # format.js { render 'show' }
      end
    end
  end

  def update
    case params[:commit]
      when '　削除　'
        @event.destroy
        respond_to do |format|
          format.html { redirect_to events_url }
          format.json { head :no_content }
        end

      when '　登録　'
        # Check param before submit
        params_valid

        if @errors.any?
          respond_to do |format|
            # init_hash_name
            format.html {render action: 'edit'}
          end
          return
        end
        # ----
        respond_to do |format|
          if @event.update(event_params)
            format.html { redirect_to events_url, notice: '更新成功作成できました。' }
            format.json { head :no_content }
          else
            format.html { render action: 'edit' }
            format.json { render json: @event.errors, status: :unprocessable_entity }
          end
        end
    end

  end
  
  def change_user
    # @events = Event.binding_event_by_change_user('1111')
    # @user = User.all
    session['selected_user'] = params[:selected_user]
    session['selected_user_name'] = params[:selected_user_name]
    
    respond_to do |format|
      format.html { redirect_to events_url}
      # format.html { render 'index'}
    end
  end
  
  def ajax
   case params[:id]
     when "event_状態コード"
       joutai = Joutaimaster.find_by 状態コード: params[:event_状態コード]
       joutai_name = joutai.try(:状態名)
       data = {joutai_name: joutai_name}
       respond_to do |format|
         format.json { render json: data}
       end
     when "event_場所コード"
       basho = Bashomaster.find_by 場所コード: params[:event_場所コード]
       basho_name = basho.try(:場所名)
       data = {basho_name: basho_name}
       respond_to do |format|
         format.json { render json: data}
       end
     when "event_工程コード"
       shain = Shainmaster.find_by 連携用社員番号: session['user_id']
       shozoku_code = shain.try(:所属コード)
       
       koutei = Kouteimaster.find_by 所属コード: shozoku_code, 工程コード: params[:event_工程コード]
       koutei_name = koutei.try(:工程名)
       
       data = {koutei_name: koutei_name}
       respond_to do |format|
         format.json { render json: data}
       end
   end
  end
  
private
# Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
    basho = Bashomaster.find_by 場所コード: @event.場所コード
    joutai = Joutaimaster.find_by 状態コード: @event.状態コード
    koutei = Kouteimaster.find_by 工程コード: @event.工程コード, 所属コード: @event.所属コード
    
    basho_name = basho.try(:場所名)
    koutei_name = koutei.try(:工程名)
    joutai_name = joutai.try(:状態名)
    
    @hash_param = { basho_name: basho_name, koutei_name: koutei_name, joutai_name: joutai_name }

  end
  
  def set_param
    @bashos = Bashomaster.all
    @joutais = Joutaimaster.all
    shain = Shainmaster.find_by 連携用社員番号: session['user_id']
    shozoku = shain.try(:所属コード)
    
    @kouteis = Kouteimaster.binding_shozoku(shozoku)
  end

# Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:社員番号, :開始, :終了, :状態コード, :場所コード, :JOB, :所属コード, :工程コード, :工数, :計上)
  end
  
  def init
    @errors = []
  end
  
  def init_hash_name
    @hash_param = { basho_name: '', koutei_name: '', joutai_name: '' }
  end

  def params_valid
    joutai_valid = params[:event][:状態コード].in? Joutaimaster.pluck :状態コード
    if !joutai_valid
      @errors.append '状態コードが間違っています'
    end

    basho_valid = params[:event][:場所コード].in? Bashomaster.pluck :場所コード
    if !basho_valid
      @errors.append '場所コードが間違っています'
    end

    shozoku_code = Shainmaster.find_by(連携用社員番号: session['user_id']).try :所属コード
    
    kouteis = Kouteimaster.where 所属コード: shozoku_code
    
    koutei_valid = params[:event][:工程コード].in? kouteis.pluck :工程コード
    if !koutei_valid
      @errors.append '工程コードが間違っています'
    end

  end
  
end

app/helpers/events_helper.rb
module EventsHelper
  def get_shozoku(shainbango)
    shain = Shainmaster.find_by 連携用社員番号: shainbango
    shozoku_code = shain.try(:所属コード)
    shozoku = Shozokumaster.find_by 所属コード: shozoku_code
    return shozoku.try(:所属名)
  end
end

app/views/events/_basho_modal.html.erb
<div class="modal fade" id="basho_search_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">場所選択</h4>
      </div>
      <div class="modal-body">
        <%# Render the new person form (passing modal => true to enable remote => true) %>

        <table id="basho_table" class="table table-striped table-bordered table-hover" cellspacing="0">
          <thead>
          <tr>
            <th>場所コード</th>
            <th>場所名</th>
          </tr>
          </thead>

          <tbody>
          <% @bashos.each do |basho| %>
              <tr>
                <td><%= basho.場所コード %></td>
                <td><%= basho.場所名 %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal" id="koutei_sentaku_ok">　ＯＫ　</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/events/_form_event.html.erb
<%= form_for @event , html:{class: 'form-horizontal', role: :form, 'data-model' => 'event'} do |f| %>
    <% if @event.errors.any? %>
        <div id="error_explanation" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
          <h2><%= @event.errors.count %> エラーが発生しました:</h2>
          <ul>
            <% @event.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    
    <!-- Error for check params-->
    <% if @errors.any? %>
        <div id="error_explanation">
          <h2>パラムエラーが発生しました：</h2>
          <ul>
            <% @errors.each do |msg| %>
                <li><%= msg %></li>
            <% end  %>
          </ul>
        </div>
    <% end %>

    <div class="spacer"></div>


    <div class="form-group">
      <%= f.label :社員番号, class: 'col-sm-2 control-label' %>
      <div class="col-sm-2">
        <%= f.text_field :社員番号, class: 'form-control', value: session['user_id'] %>
      </div>
      
      <% if mode != 'new' %>
          <% if @event.計上 == '済'%>
            <%= f.label :計上, class: 'col-sm-2 control-label' %>
            <!--<div class="col-sm-2">-->
              <%# f.text_field :計上, class: 'form-control' %>
              <span class="col-sm-1 control-label"><%= @event.計上 %>　　　　</span>
            <!--</div>-->
              <% end %>
      <% end  %>
      
      <span id="shainbango" class="help-block"></span>
    </div>    
    
    <div class="form-group">
      <%= f.label :開始, class: 'col-sm-2 control-label' %>
      <div class="col-md-2">
          <%= f.text_field :開始, class: 'form-control' %>
      </div>
      
      <span id="start_date" class="help-block"></span>
    </div>

    <div class="form-group">
      <%= f.label :終了, class: 'col-sm-2 control-label' %>
      
      <div class="col-md-2">
        <%= f.text_field :終了, class: 'form-control' %>
      </div>
      
      <span id="end_date" class="help-block"></span>
    </div>

    <div class="form-group">
      <%= f.label :状態, class: 'col-sm-2 control-label' %>
      <div class="col-sm-2">
        <%= f.text_field :状態コード, class: 'form-control' %>
      </div>
      <div class="col-md-1">
        <button class="btn btn-default" id="joutai_search" type="button">
          <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
        </button>
      </div>
        <span id="joutai_name"><%= @hash_param[:joutai_name] %></span>
      <span class="help-block"></span>
    </div>
    
    <div class="form-group">
      <%= f.label :場所, class: 'col-sm-2 control-label' %>
      <div class="col-sm-2">
        <%= f.text_field :場所コード, class: 'form-control' %>
      </div>
      <div class="col-md-1">
        <button class="btn btn-default" id="basho_search" type="button">
          <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
        </button>
      </div>
      <span id="basho_name"><%= @hash_param[:basho_name] %></span>
      <span class="help-block"></span>
    </div>
    
    <div class="form-group">
      <%= f.label :JOB, class: 'col-sm-2 control-label' %>
      <div class="col-sm-2">
        <%= f.text_field :JOB, class: 'form-control' %>
      </div>
      <span class="help-block"></span>
    </div>
    
    <%= f.hidden_field :所属コード, class: 'form-control' %>
    
    <div class="form-group">
      <%= f.label :工程, class: 'col-sm-2 control-label' %>
      <div class="col-sm-2">
        <%= f.text_field :工程コード, class: 'form-control' %>
      </div>
      <div class="col-md-1">
        <button class="btn btn-default" id="koutei_search" type="button">
          <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
        </button>
      </div>
      <span id="koutei_name"><%= @hash_param[:koutei_name] %></span>
      <span class="help-block"></span>
    </div>
    
    <div class="form-group">
      <%= f.label :工数, class: 'col-sm-2 control-label' %>
      <div class="col-sm-2">
        <%= f.text_field :工数, class: 'form-control' %>
      </div>
      <span class="help-block"></span>
    </div>
    
    <% if session['selected_user'] == session['user_id'] && @event.計上 != '済' %>
        <div class="form-group">
          <div class="col-sm-1 col-sm-offset-2">
            <%= f.submit '　登録　', class: 'btn btn-primary' %>
          </div>
          <% if mode == 'edit' %>
              <div class="col-sm-1">
                <%= f.submit '　削除　', class: 'btn btn-default' %>
              </div>
          <% end %>
        </div>
    <% end %>
<% end %>

<%= render 'joutai_modal' %>
<%= render 'basho_modal' %>
<%= render 'koutei_modal' %>

app/views/events/_joshoku_modal.html.erb
<div class="modal fade" id="select_user_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">社員選択</h4>
      </div>
      <div class="modal-body">
        <%# Render the new person form (passing modal => true to enable remote => true) %>

        <table id="user_table" class="table table-striped table-bordered table-hover" cellspacing="0">
          <thead>
          <tr>
            <th>担当者コード</th>
            <th>担当者名称</th>
          </tr>
          </thead>

          <tbody>
          <% @joshoku.each do |joshoku| %>
              <tr>
                <td><%= joshoku.担当者コード %></td>
                <td><%= joshoku.担当者名称 %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal" id="koutei_sentaku_ok">　ＯＫ　</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/events/_joutai_modal.html.erb
<div class="modal fade" id="joutai_search_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">状態選択</h4>
      </div>
      <div class="modal-body">
        <%# Render the new person form (passing modal => true to enable remote => true) %>

        <table id="joutai_table" class="table table-striped table-bordered table-hover" cellspacing="0">
          <thead>
          <tr>
            <th>状態コード</th>
            <th>状態名</th>
          </tr>
          </thead>

          <tbody>
          <% @joutais.each do |joutai| %>
              <tr>
                <td><%= joutai.状態コード %></td>
                <td><%= joutai.状態名 %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal" id="koutei_sentaku_ok">　ＯＫ　</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/events/_koutei_modal.html.erb
<div class="modal fade" id="koutei_search_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">工程選択</h4>
      </div>
      <div class="modal-body">
        <%# Render the new person form (passing modal => true to enable remote => true) %>
        <div class="row">
          <div class="col-md-2">
            <span>所属:</span>
          </div>
          <div class="col-md-2">
            <span><%= @kouteis[0].所属コード %></span>
          </div>
          <div class="col-md-2">
            <span><%= @kouteis[0].所属名 %></span>
          </div>
        </div>
        <div class="spacer"></div>
        <table id="koutei_table" class="table table-striped table-bordered table-hover" cellspacing="0">
          <thead>
          <tr>
            <th>工程コード</th>
            <th>工程名</th>
          </tr>
          </thead>

          <tbody>
          <% @kouteis.each do |koutei| %>
              <tr>
                <td><%= koutei.工程コード %></td>
                <td><%= koutei.工程名 %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal" id="koutei_sentaku_ok">　ＯＫ　</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<%= javascript_include_tag 'event' %>

<ol class="breadcrumb">
  <li><%= link_to 'メニュー', main_path %></li>
  <li><%= link_to 'カレンダー', events_path %></li>
  <li class="active">イベント</li>
</ol>

<%= render 'form_event', mode: 'edit' %>

app/views/events/index.html.erb
<%= javascript_include_tag 'event' %>
<%= javascript_include_tag 'resource/ja' %>

<div class="row">
  <div class="col-md-12">
    <ol class="breadcrumb">
      <li><%= link_to 'メニュー', main_path %></li>
      <!-- <li><a href="#">基準情報</a></li> -->
      <!-- <li><a href="#">セキュリティ管理</a></li> -->
      <li class="active">カレンダー</li>
    </ol>
  </div>
</div>
<div class="row">
  <div class="col-md-2 col-md-offset-6">
    <h3><span class="label label-default">氏名：　<%= session['selected_user_name'] %></span></h3>
  </div>
</div>

<div class="row">
  <div class="col-md-2">
    <input type='text' class="form-control" id="goto-date-input" name="goto-date-input" placeholder="YYYY/MM/DD" >
  </div>
  <div class="col-md-1">
    <button id="goto-date-button" class="btn btn-default" type="button">Goto</button>
  </div>

  <div class="col-md-2 col-md-offset-3">
    <h4>役員G：　<%= get_shozoku(session['selected_user']) %></h4>
  </div>

  <div class="col-md-1 col-md-offset-1">
    <%# button_to '社員選択', %>
    <button class="btn btn-default" id="search_user">社員選択</button>
  </div>

</div>

<div class="row">
  <div class="col-md-12">
    <div class="spacer">
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">

    <table id="event_table" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
      <thead>
      <tr>
        <th></th>
        <th>開始時刻</th>
        <th>終了時刻</th>
        <th>状態</th>
        <th>場所／用件</th>
        <th>JOB No.</th>
        <th>工程名</th>
        <th>工数</th>
        <th>計上</th>
      </tr>
      </thead>

      <tbody>
<% @events.each do |event| %>
      <tr>
        <td><%= event.id %></td>
        <td><%= event.開始 %></td>
        <td><%= event.終了 %></td>
        <td><%= event.状態名 %></td>
        <td><%= event.場所名 %></td>
        <td><%= event.JOB %></td>
        <td><%= event.工程名 %></td>
        <td><%= event.工数 %></td>
        <td><%= event.計上 %></td>
      </tr>
<% end %>


      <%# @events.each do |event| %>
      <%# render partial: 'table_row', locals: {event: event} %>
      <%# end %>
      </tbody>
    </table>
  </div>

</div>

  <div class="row">
    <div class="col-md-2">
      <%= link_to "新規イベント", new_event_path %>
    </div>
  </div>

<div class="row">
  <div class="col-md-12">
    <div class="spacer">
    </div>
  </div>
</div>
<legend></legend>
<div class="row">
  <div class="col-md-12">
    <div id="calendar"></div>
  </div>
</div>

<%= form_for :user, url: change_user_events_path  do |f| %>
    <%# render 'select_user_modal' %>
    <div class="modal fade" id="select_user_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">社員選択</h4>
          </div>
          <div class="modal-body">
            <%# Render the new person form (passing modal => true to enable remote => true) %>

            <table id="user_table" class="table table-striped table-bordered table-hover" cellspacing="0">
              <thead>
              <tr>
                <th>社員番号</th>
                <th>氏名</th>
              </tr>
              </thead>

              <tbody>
              <% @shains.each do |shain| %>
                  <tr>
                    <td><%= shain.連携用社員番号 %></td>
                    <td><%= shain.氏名 %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary"  id="koutei_sentaku_ok">　ＯＫ　</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
          </div>
        </div>
      </div>
    </div>
    <input type="hidden" name="selected_user" id="selected_user"/>
    <input type="hidden" name="selected_user_name" id="selected_user_name"/>
<% end %>

app/views/events/new.html.erb
<%= javascript_include_tag 'event' %>

<ol class="breadcrumb">
  <li><%= link_to 'メニュー', main_path %></li>
  <li><%= link_to 'カレンダー', events_path %></li>
  <!-- <li><a href="#">基準情報</a></li> -->
  <!-- <li><a href="#">セキュリティ管理</a></li> -->
  <li class="active">イベント</li>
</ol>

<%= render 'form_event', mode: 'new' %>