config/routes.rb
Jpt::Application.routes.draw do

  resources :shainmasters, only: [:index] do
    
  end
  
  resources :shozokumasters, only: [:index] do
    
  end
  resources :joutaimasters, only: [:index] do
    
  end
resources :bashomasters, only: [:index] do
    
  end

  # get 'events/index'

  get 'joutaimasters/index'

  get 'bashomaster/index'

  resources :events, only: [:index, :new, :create, :edit, :update] do
		collection do
			post :change_user
			post :ajax
		end
	end
	
  resources :kouteimasters do
    collection do
      post :ajax
    end
  end

  # get "shozais/index"
  post "shozais/select"
	resources :shozais do
		collection do
			# post :getAjax
			get :main
		end
	end

	root to: 'users#login'

	# post 'users/login'

	# match 'login', to: 'users#create', via: [:post]
	# match 'change_pass', to: 'users#change_pass', via: [:get,:post]
	# match 'change_pass_exc', to: 'users#change_pass_exc', via: [:get,:post]

	match 'main', to: 'main#index', via: [:get]

	match 'tree', to: 'tree#index', via: [:get]
	match 'call_by_ajax', to: 'tree#getAjax', via: [:post]
	match 'uploadFile', to: 'tree#upload', via: [:get,:post]
	match 'email', to: 'tree#email', via: [:get,:post]
	match 'emailxhr', to: 'tree#emailxhr', via: [:post]
	match 'scroll', to: 'tree#scroll', via: [:get,:post]

	# match 'multiselect', to: 'tree#multiselect', via: [:get,:post]
	# match 'employer', to: 'tree#employer', via: [:get,:post]

	# resources :employers, only: [:index, :create, :new, :edit, :show, :update, :destroy]
  resources :users, only: [:create, :new] do
    collection do
      get :login
    end
  end
  resources :employers

end

app/models/Employer.rb
class Employer < ActiveRecord::Base
  self.table_name = 'employer'
  # validates :email, confirmation: true
  # validates :email, presence: true
  # validates :email_confirmation, presence: true
end

app/models/base_model.rb
class BaseModel < ActiveRecord::Base
  def message
    @message
  end
  
  def message= (msg)
    @message = msg
  end
  # createモード, editモード　：　フォームのactionに指定します。
  def action_name
    @action_name
  end
  
  def action_name= (action)
    @action_name = action
  end
end

app/models/bashomaster.rb
class Bashomaster < ActiveRecord::Base
  self.table_name = '場所マスタ'
end

app/models/employer.rb
class Employer < ActiveRecord::Base
  self.table_name = 'employer'
  # validates :email, confirmation: true
  validates :first_name, presence: true
  validates :age, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
  self.table_name = 'events'
  validates :開始, presence: true
  validates :状態コード, presence: true
  validates :場所コード, presence: true
  validates :工程コード, presence: true

  def self.binding_event_by_change_user(user_id)
    sql = "SELECT a.*, b.場所名, c.状態名, d.工程名"
    sql << " FROM events a LEFT OUTER JOIN 場所マスタ b ON a.場所コード = b.場所コード"
    sql << " LEFT OUTER JOIN 状態マスタ c on a.状態コード = c.状態コード"
    sql << " LEFT OUTER JOIN 工程マスタ d on a.所属コード = d.所属コード and a.工程コード = d.工程コード"
    sql << " WHERE a.社員番号 = '#{user_id}'"
    @events = Event.find_by_sql(sql) 
    # @events.each do |event|
    #   if event.終了.nil?
    #     event.終了 = Date.tomorrow.to_s
    #   end
    # end
    # return @events
  end
end

app/models/joutaimaster.rb
class Joutaimaster < ActiveRecord::Base
  self.table_name = '状態マスタ'
end

app/models/kouteimaster.rb
class Kouteimaster < ActiveRecord::Base
  self.table_name = '工程マスタ'
  validates :工程コード, presence: true
  validates :工程名, presence: true

  def self.binding_shozoku(shozoku)
    sql = "SELECT a.*, b.所属名"
    sql << " FROM 工程マスタ a LEFT OUTER JOIN 所属マスタ b ON a.所属コード = b.所属コード"
    sql << " WHERE a.所属コード = '#{shozoku}'"
     koutei = Kouteimaster.find_by_sql(sql)
    return koutei

  end
end

app/models/sagyou.rb
class Sagyou < ActiveRecord::Base
  self.table_name = '作業場所マスタ'
end

app/models/sample.rb
class Sample < ActiveRecord::Base
	def self.save(upload)
		name = upload['datafile']
		directory = "public/data"
		# create the file path
		path = File.join(directory, name)
		#write the file
		File.open(path, "wb"){|f| f.write(upload['datafile'].read)
		}
	end
end

app/models/shainmaster.rb
class Shainmaster < ActiveRecord::Base
  self.table_name = '社員マスタ'
end

app/models/shozai.rb
class Shozai < ActiveRecord::Base
  self.table_name = '所在マスタ'

end

app/models/shozokumaster.rb
class Shozokumaster < ActiveRecord::Base
  self.table_name = '所属マスタ'
end

app/models/tree.rb
class Tree < ActiveRecord::Base


end

app/models/user.rb
class User < ActiveRecord::Base
  self.table_name = '担当者マスタ'
  # validates :email, confirmation: true
  validates :担当者コード, presence: true
  # validates :email_confirmation, presence: true
end

app/models/yakushoku.rb
class Yakushoku < ActiveRecord::Base
  self.table_name = '役職テープル'
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_employer, only: [:show, :edit, :update, :destroy]

  def index
    # get all record
    @employers = Employer.all
    @employer = Employer.new

  end

  def edit
  end

  def show

  end

  def create
    if params[:add]
      if  !params[:clicked_index].empty?
        # Update
        id = params[:employer][:id]
        @employer = Employer.find(id)
        respond_to do |format|
          if @employer.update(employer_params)
            format.js {render 'update'}
          else
            # format.js {render 'empty'}
            format.js { render json: @employer.errors, status: :unprocessable_entity }
          end
        end

      else
        # New
        @employer = Employer.new(employer_params)

        respond_to do |format|
            if @employer.save
              format.html { redirect_to @employer, notice: '新規成功出来ました。' }
              format.json { render action: 'show', status: :created, location: @employer }
              # format.js { render 'index', status: :created, location: @employer }
              format.js {}
            else
              format.html { render action: 'new' }
              format.json { render json: @employer.errors, status: :unprocessable_entity }
              format.js { render json: @employer.errors, status: :unprocessable_entity }
              # format.js { render 'show' }
            end
          end
      end
    # delete
    else if !params[:delete].nil?
      		params[:delete].each do |id,value|
      			Employer.find(id.to_i).destroy
      		end
      		respond_to do |format|
      			format.html{}
      			format.json{}
      			format.js{render 'destroy'}
      		end
        else
          respond_to do |format|
            format.js {render 'empty'}
          end
        end
    end

  end

  def update
    respond_to do |format|
      if @employer.update(employer_params)
        format.html { redirect_to @employer, notice: '更新成功できました。' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_employer
    @employer = Employer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def employer_params
    params.require(:employer).permit(:first_name, :position, :office, :age, :start_date, :salary, :id)
  end

end

app/helpers/events_helper.rb
module EventsHelper
  def get_shozoku(shainbango)
    shain = Shainmaster.find_by 連携用社員番号: shainbango
    shozoku_code = shain.try(:所属コード)
    shozoku = Shozokumaster.find_by 所属コード: shozoku_code
    return shozoku.try(:所属名)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/koutei_helper.rb
module KouteiHelper
end

app/helpers/shain_helper.rb
module ShainHelper
end

app/helpers/shozai_helper.rb
module ShozaiHelper
end

app/helpers/tantoshas_helper.rb
module TantoshasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/employers/_table_row.html.erb
<tr>
  <td><%= check_box_tag "delete[#{employer.id}]", 1 %></td>
  <td><%= employer.first_name %></td>
  <td><%= employer.position %></td>
  <td><%= employer.office %></td>
  <td><%= employer.age %></td>
  <td><%= employer.start_date %></td>
  <td><%= employer.salary %></td>
  <td><%= employer.id %></td>
</tr>

app/views/employers/create.js.erb
//hide modal
//    $('#new_employer_modal').modal('hide');
//add row
//    $('#multiselect_table').append("<%# j render partial: 'table_row', locals: {employer: @employer } %>");

//refresh the page
//window.location.reload();
//oTable.ajax.reload();
//oTable.draw(true);
oTable.row.add([
        '<input type="checkbox" name="delete[<%= @employer.id %>]" id="delete_<%= @employer.id %>" value="1">',
        '<%= @employer.first_name %>',
        '<%= @employer.position %>',
        '<%= @employer.office %>',
        '<%= @employer.age %>',
        '<%= @employer.start_date %>',
        '<%= @employer.salary %>',
        '<%= @employer.id %>'
]).draw();

//$('#multiselect_table INPUT').click(function() {
//    $(this).parent().parent().toggleClass('success');
//});

$('#delete_<%= @employer.id %>').click(function() {
    $(this).parent().parent().toggleClass('success');
});

//$('#multiselect_table tbody').on( 'click', 'tr', function () {
//    $(this).toggleClass('selected');
//} );

//clear modal error
$('#new_employer_modal').modal_success();

app/views/employers/destroy.js.erb
//clear deleted mark rows
    oTable.row('.success').remove().draw(false);

app/views/employers/edit.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'メニュー', main_path %></li>
  <!-- <li><a href="#">基準情報</a></li> -->
  <!-- <li><a href="#">セキュリティ管理</a></li> -->
  <li class="active">MultiSelect Edit</li>
</ol>

<h1>Edit Selected row</h1>

<%= form_for @employer, html: {class: 'horizontal', role: 'form', 'data-model' => 'employer'}, method: 'post' do |f| %>
<div class="form-group">
  <%= f.label :お名前, class: 'control-label' %><br>
  <%= f.text_field :first_name, class: 'form-control' %>
  <span class="help-block"></span>
</div>

<%# Added Bootstrap classes, and help-block container for error messages %>
<div class="form-group">
  <%= f.label :位置, class: 'control-label' %><br>
  <%= f.text_field :position, class: 'form-control' %>
  <span class="help-block"></span>
</div>

<%# Added Bootstrap classes, and help-block container for error messages %>
<div class="form-group">
  <%= f.label :オフィス, class: 'control-label' %><br>
  <%= f.text_field :office, class: 'form-control' %>
  <span class="help-block"></span>
</div>

<%# Added Bootstrap classes, and help-block container for error messages %>
<div class="form-group">
  <%= f.label :年齢, class: 'control-label' %><br>
  <%= f.text_field :age, class: 'form-control' %>
  <span class="help-block"></span>
</div>

<%# Added Bootstrap classes, and help-block container for error messages %>
<div class="form-group">
  <%= f.label :開始日, class: 'control-label' %><br>
  <%= f.text_field :start_date, class: 'form-control' %>
  <span class="help-block"></span>
</div>

<%# Added Bootstrap classes, and help-block container for error messages %>
<div class="form-group">
  <%= f.label :給料, class: 'control-label' %><br>
  <%= f.text_field :salary, class: 'form-control' %>
  <span class="help-block"></span>
</div>

<%# Added Bootstrap classes %>
<div class="actions">
  <%= f.submit 'Update', class: 'btn btn-default', name: 'update' %>
</div>
</div>
<% end %>

app/views/employers/index.erb
<%= javascript_include_tag 'employer' %>
<ol class="breadcrumb">
  <li><%= link_to 'メニュー', main_path %></li>
  <!-- <li><a href="#">基準情報</a></li> -->
  <!-- <li><a href="#">セキュリティ管理</a></li> -->
  <li class="active">Multiselect</li>
</ol>

<h1>マルティセレクト（複数選択）</h1>
<%= form_for @employer, url: employers_path, html:{'data-model' => 'employer'}, remote: true, method: 'post' do |f| %>
<div class="col-md-3 col-md-offset-2"> </div>
<div class="btn-group" role="group" aria-label="...">
  <button id="add_new_employer" type="button" class="btn btn-default">　
  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>　
  </button>
  <button type="submit" class="btn btn-default" name="multidelete">　
    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>　
  </button>
</div>


<table id="multiselect_table" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
  <thead>
  <tr>
    <th><%= check_box_tag "delete_all", 1 %></th>
    <th>Name</th>
    <th>Position</th>
    <th>Office</th>
    <th>Age</th>
    <th>Start date</th>
    <th>Salary</th>
    <th></th>
  </tr>
  </thead>

  <tfoot>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Position</th>
    <th>Office</th>
    <th>Age</th>
    <th>Start date</th>
    <th>Salary</th>
    <th></th>
  </tr>
  </tfoot>

  <tbody>
  <% @employers.each do |employer| %>
      <%= render partial: 'table_row', locals: {employer: employer} %>
  <% end %>
  </tbody>
</table>


<%# link_to 'New Person', '#new_person_modal', 'data-toggle' => 'modal' %>

<%# Bootstrap modal markup. @see: http://getbootstrap.com/javascript/#modals %>
<div class="modal fade" id="new_employer_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">追加情報入力</h4>
      </div>
      <div class="modal-body">
        <%# Render the new person form (passing modal => true to enable remote => true) %>
         <%# render 'modal_form' %>
        <%# Added Bootstrap classes, and help-block container for error messages %>
        <div class="form-group">
          <%= f.label :お名前, class: 'control-label' %><br>
          <%= f.text_field :first_name, class: 'form-control' %>
          <span class="help-block"></span>
        </div>

        <%# Added Bootstrap classes, and help-block container for error messages %>
        <div class="form-group">
          <%= f.label :位置, class: 'control-label' %><br>
          <%= f.text_field :position, class: 'form-control' %>
          <span class="help-block"></span>
        </div>

        <%# Added Bootstrap classes, and help-block container for error messages %>
        <div class="form-group">
          <%= f.label :オフィス, class: 'control-label' %><br>
          <%= f.text_field :office, class: 'form-control' %>
          <span class="help-block"></span>
        </div>

        <%# Added Bootstrap classes, and help-block container for error messages %>
        <div class="form-group">
          <%= f.label :年齢, class: 'control-label' %><br>
          <%= f.text_field :age, class: 'form-control' %>
          <span class="help-block"></span>
        </div>

        <%# Added Bootstrap classes, and help-block container for error messages %>
        <div class="form-group">
          <%= f.label :開始日, class: 'control-label' %><br>
          <%= f.text_field :start_date, class: 'form-control' %>
          <span class="help-block"></span>
        </div>

        <%# Added Bootstrap classes, and help-block container for error messages %>
        <div class="form-group">
          <%= f.label :給料, class: 'control-label' %><br>
          <%= f.text_field :salary, class: 'form-control' %>
          <span class="help-block"></span>
        </div>

        <div>
          <%= f.hidden_field :id %>
        </div>
        <%# Added Bootstrap classes %>
        <div class="actions">
          <%= f.submit '更新', class: 'btn btn-default', name: 'add' %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>
    <input type="hidden" id="clicked_index" name="clicked_index"/>
<% end %>

<div id="calendar"></div>

app/views/employers/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'メニュー', main_path %></li>
  <!-- <li><a href="#">基準情報</a></li> -->
  <!-- <li><a href="#">セキュリティ管理</a></li> -->
  <li class="active">MultiSelect Show</li>
</ol>

<h1>Show selected row info</h1>


<p>
  <strong>First Name:</strong>
  <%= @employer.first_name %>
</p>

<p>
  <strong>Office:</strong>
  <%= @employer.office %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @employer.salary %>
</p>

app/views/employers/update.js.erb
idx = $('#clicked_index').val();
var d = oTable.row( idx ).data();

d[1] = '<%= @employer.first_name %>';
d[2] = '<%= @employer.position %>';
d[3] = '<%= @employer.office %>';
d[4] = '<%= @employer.age %>';
d[5] = '<%= @employer.start_date %>';
d[6] = '<%= @employer.salary %>';

oTable.row( idx ).data( d );
oTable.draw();

$('#delete_<%= @employer.id %>').click(function() {
    $(this).parent().parent().toggleClass('success');
});

////for handle ajax error
//$(function () {
//    $(document).bind('ajaxError', 'form#new_employer', function (event, jqxhr, settings, exception) {
//        // note: jqxhr.responseJSON undefined, parsing responseText instead
//        $(event.data).render_form_errors($.parseJSON(jqxhr.responseText));
//    });
//
//    //$(document).bind('ajaxSuccess', 'form#new_kouteimaster', function (event, jqxhr, settings, exception) {
//    //    // note: jqxhr.responseJSON undefined, parsing responseText instead
//    //    $(location).attr('href','/kouteimasters');
//    //});
//});

//clear modal error
$('#new_employer_modal').modal_success();