config/routes.rb
Jpt::Application.routes.draw do

  resources :shainmasters, only: [:index] do
    
  end
  
  resources :shozokumasters, only: [:index] do
    
  end
  resources :joutaimasters, only: [:index] do
    
  end
resources :bashomasters, only: [:index] do
    
  end

  # get 'events/index'

  get 'joutaimasters/index'

  get 'bashomaster/index'

  resources :events, only: [:index, :new, :create, :edit, :update] do
		collection do
			post :change_user
			post :ajax
		end
	end
	
  resources :kouteimasters do
    collection do
      post :ajax
    end
  end

  # get "shozais/index"
  post "shozais/select"
	resources :shozais do
		collection do
			# post :getAjax
			get :main
		end
	end

	root to: 'users#login'

	# post 'users/login'

	# match 'login', to: 'users#create', via: [:post]
	# match 'change_pass', to: 'users#change_pass', via: [:get,:post]
	# match 'change_pass_exc', to: 'users#change_pass_exc', via: [:get,:post]

	match 'main', to: 'main#index', via: [:get]

	match 'tree', to: 'tree#index', via: [:get]
	match 'call_by_ajax', to: 'tree#getAjax', via: [:post]
	match 'uploadFile', to: 'tree#upload', via: [:get,:post]
	match 'email', to: 'tree#email', via: [:get,:post]
	match 'emailxhr', to: 'tree#emailxhr', via: [:post]
	match 'scroll', to: 'tree#scroll', via: [:get,:post]

	# match 'multiselect', to: 'tree#multiselect', via: [:get,:post]
	# match 'employer', to: 'tree#employer', via: [:get,:post]

	# resources :employers, only: [:index, :create, :new, :edit, :show, :update, :destroy]
  resources :users, only: [:create, :new] do
    collection do
      get :login
    end
  end
  resources :employers

end

app/models/Employer.rb
class Employer < ActiveRecord::Base
  self.table_name = 'employer'
  # validates :email, confirmation: true
  # validates :email, presence: true
  # validates :email_confirmation, presence: true
end

app/models/base_model.rb
class BaseModel < ActiveRecord::Base
  def message
    @message
  end
  
  def message= (msg)
    @message = msg
  end
  # createモード, editモード　：　フォームのactionに指定します。
  def action_name
    @action_name
  end
  
  def action_name= (action)
    @action_name = action
  end
end

app/models/bashomaster.rb
class Bashomaster < ActiveRecord::Base
  self.table_name = '場所マスタ'
end

app/models/employer.rb
class Employer < ActiveRecord::Base
  self.table_name = 'employer'
  # validates :email, confirmation: true
  validates :first_name, presence: true
  validates :age, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
  self.table_name = 'events'
  validates :開始, presence: true
  validates :状態コード, presence: true
  validates :場所コード, presence: true
  validates :工程コード, presence: true

  def self.binding_event_by_change_user(user_id)
    sql = "SELECT a.*, b.場所名, c.状態名, d.工程名"
    sql << " FROM events a LEFT OUTER JOIN 場所マスタ b ON a.場所コード = b.場所コード"
    sql << " LEFT OUTER JOIN 状態マスタ c on a.状態コード = c.状態コード"
    sql << " LEFT OUTER JOIN 工程マスタ d on a.所属コード = d.所属コード and a.工程コード = d.工程コード"
    sql << " WHERE a.社員番号 = '#{user_id}'"
    @events = Event.find_by_sql(sql) 
    # @events.each do |event|
    #   if event.終了.nil?
    #     event.終了 = Date.tomorrow.to_s
    #   end
    # end
    # return @events
  end
end

app/models/joutaimaster.rb
class Joutaimaster < ActiveRecord::Base
  self.table_name = '状態マスタ'
end

app/models/kouteimaster.rb
class Kouteimaster < ActiveRecord::Base
  self.table_name = '工程マスタ'
  validates :工程コード, presence: true
  validates :工程名, presence: true

  def self.binding_shozoku(shozoku)
    sql = "SELECT a.*, b.所属名"
    sql << " FROM 工程マスタ a LEFT OUTER JOIN 所属マスタ b ON a.所属コード = b.所属コード"
    sql << " WHERE a.所属コード = '#{shozoku}'"
     koutei = Kouteimaster.find_by_sql(sql)
    return koutei

  end
end

app/models/sagyou.rb
class Sagyou < ActiveRecord::Base
  self.table_name = '作業場所マスタ'
end

app/models/sample.rb
class Sample < ActiveRecord::Base
	def self.save(upload)
		name = upload['datafile']
		directory = "public/data"
		# create the file path
		path = File.join(directory, name)
		#write the file
		File.open(path, "wb"){|f| f.write(upload['datafile'].read)
		}
	end
end

app/models/shainmaster.rb
class Shainmaster < ActiveRecord::Base
  self.table_name = '社員マスタ'
end

app/models/shozai.rb
class Shozai < ActiveRecord::Base
  self.table_name = '所在マスタ'

end

app/models/shozokumaster.rb
class Shozokumaster < ActiveRecord::Base
  self.table_name = '所属マスタ'
end

app/models/tree.rb
class Tree < ActiveRecord::Base


end

app/models/user.rb
class User < ActiveRecord::Base
  self.table_name = '担当者マスタ'
  # validates :email, confirmation: true
  validates :担当者コード, presence: true
  # validates :email_confirmation, presence: true
end

app/models/yakushoku.rb
class Yakushoku < ActiveRecord::Base
  self.table_name = '役職テープル'
end

app/controllers/tree_controller.rb
class TreeController < ApplicationController
  skip_before_action :verify_authenticity_token
	
	def index

		@records = []
		record = {}
		record['端末番号']=452267
		record['表示ラベル']='30011091  豚の生姜焼95G 20*2            梱    2010/10/27〜2099/12/31【試作品】'
		record['レベル']='1'
		record['ツリー順序']='1'
		record['品目区分']='6'
		@records[0] = record

		record = {}
		record['端末番号']=452267
		record['表示ラベル']='30011092  豚の生姜焼95G 20*2            梱    '
		record['レベル']='2'
		record['ツリー順序']='2'
		record['品目区分']='4'
		@records[1] = record

		record = {}
		record['端末番号']=452267
		record['表示ラベル']='30011093  豚の生姜焼95G 20*2            梱    '
		record['レベル']='2'
		record['ツリー順序']='3'
		record['品目区分']='5'
		@records[2] = record
		
		@m001tree = {}
		@m001tree['kozo_code']           = '99999999'#params[:kozo_code]
		@m001tree['kozo_name']           = '富士通工場'#params[:kozo_name]
		@m001tree['hinme_code']          = '12345678'#params[:hinme_code]
		@m001tree['hinme_name']          = 'カードリーダ'#params[:hinme_name]
		@m001tree['kijunbi']             = '2012/17/01'#params[:kijunbi]
		@m001tree['nisugata']            = 'バグ'#params[:nisugata]
		@m001tree['selected_hinme_code'] = '12345678'#params[:selected_hinme_code]
	end

	def getAjax
		id = params[:id]
    case id
    when 'header_hinme'
      hinme_code = params[:hinme_code]
      hinme_name = 'Hoang Minh Duc'
      respond_to do |format|
        data = {hinme_name: hinme_name }
        format.json {render json: data}
      end
    end
	end

	def upload
		if request.post?
			uploaded_io = params[:person][:picture]
		  File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
		    file.write(uploaded_io.read)
		  end
		end
	end

	def email
		flash[:notice] = ""
		@user = User.find_by(担当者コード: "9999")
		if request.post?
			email = params[:user][:email]
			if email == "hminhduc@gmail.com"
				flash[:notice] = "Someone already has that username. Try another?"
			else
				@user.email = email
				@user.save
			end
		end
	end

	def emailxhr
		email = params[:email]
		if email == "hminhduc@gmail.com"
			respond_to do |format|
				# format.html {render 'email'}
				# format.js {render 'email'}
				data = {error: "true" }
				format.json {render json: data}
			end
		end
	end

	def scroll
		
	end

end

app/helpers/events_helper.rb
module EventsHelper
  def get_shozoku(shainbango)
    shain = Shainmaster.find_by 連携用社員番号: shainbango
    shozoku_code = shain.try(:所属コード)
    shozoku = Shozokumaster.find_by 所属コード: shozoku_code
    return shozoku.try(:所属名)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/koutei_helper.rb
module KouteiHelper
end

app/helpers/shain_helper.rb
module ShainHelper
end

app/helpers/shozai_helper.rb
module ShozaiHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tree/_header.html.erb
<!-- <form class="form-horizontal" action="/index" role="form"> -->
<div class="col-md-6">

  <div class="form-group">
    <label for="kozososiki_label" class="col-sm-2 control-label">工場組織：</label>
    <div class="col-xs-3">
      <input type="text" class="form-control" id="header_kozo" name="m001tree[kozo_code]" placeholder="工場組織コード" value= <%= @m001tree['kozo_code'] %>  >
    </div>
    <div class="col-xs-5">
      <input type="text" class="form-control" id="header_kozo_name" name="m001tree[kozo_name]" placeholder="工場組織名称" value= <%= @m001tree['kozo_name'] %>>
    </div>
  </div>

  <div class="form-group">
    <label for="hinme_label" class="col-sm-2 control-label">品目：</label>
    <div class="col-xs-3">
      <input type="text" class="form-control" id="header_hinme" name="m001tree[hinme_code]" placeholder="品目コード" value= <%= @m001tree['hinme_code'] %> >
    </div>
    <div class="col-xs-5">
      <input type="text" class="form-control" id="header_hinme_name" name="m001tree[hinme_name]" placeholder="品目名称" value= <%= @m001tree['hinme_name'] %>>
    </div>
    <button type="button" class="btn btn-default" id="hinme_search">🔎</button>
  </div>

  <div class="form-group">
    <label for="kijunbi_label" class="col-sm-2 control-label">基準日：</label>
    <div class="col-md-4">
      <div class='input-group date' id='datetimepicker5' data-date-format="YYYY/MM/DD">
        <input type='text' class="form-control" id="header_kijunbi" name="m001tree[kijunbi]" placeholder="2012/01/17" value= <%= @m001tree['kijunbi'] %> >
            <span class="input-group-addon"><span class="glyphicon glyphicon-time"></span>
            </span>
      </div>
    </div>
  </div>

</div>

<div class="col-md-6">
  <div class="form-group">
    <label for="tani_label" class="col-sm-2 control-label">荷姿単位：</label>
    <div class="col-md-3">
      <div class="input-group">
        <input class="form-control" id="header_tani" size="4" type="text" name="m001tree[nisugata]" value=<%= @m001tree['nisugata'] %>>
			    <span class="input-group-addon dropdown-toggle" data-toggle="dropdown">
			        <span class="caret"></span>
			    </span>
        <ul class="dropdown-menu" id="tani_select">
        </ul>
      </div>
    </div>
  </div>

  <p><br></p>
  <p><br></p>

  <div class="col-md-8 col-md-offset-4"  style="margin-bottom: 5px">

    <button type="submit" class="btn btn-primary" id="search">　検　索　</button>
    <button type="submit" class="btn btn-primary" id="cancel">キャンセル</button>
    <button type="submit" class="btn btn-primary" id="close">　閉じる　</button>
    <input  type="hidden" value="" name="m001tree[selected_button]" id="selected_button">

  </div>
</div>
<!-- </form> -->

<legend></legend>

<%= render 'hinme_search_modal' %>

app/views/tree/_hinme_search_modal.html.erb
<%# Bootstrap modal markup. @see: http://getbootstrap.com/javascript/#modals %>
<div class="modal fade" id="hinme_search_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">品目選択</h4>
      </div>
      <div class="modal-body">
        <%# Render the new person form (passing modal => true to enable remote => true) %>
        <%= render 'hinme_search_modal_table' %>
      </div>
      <div class="modal-footer">
        <button id="btn_hinme_search_ok" type="button" class="btn btn-default" data-dismiss="modal">　OK　</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/tree/_hinme_search_modal_table.html.erb
<table id="hinme_search_table" class="table table-striped table-bordered table-hover" cellspacing="0">

  <thead>
    <tr>
      <th>品目コード</th>
      <th>品目名</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td>99999998</td>
        <td>Macbook Air</td>
      </tr>
      <tr>
        <td>99999999</td>
        <td>Ipad Air 2</td>
      </tr>
  </tbody>
</table>

app/views/tree/_main.html.erb
<div class="col-md-3">
	<div style="margin-top: 40px"></div>
	<ul class="media-list">

	  <li class="media">
	    <a class="pull-left">
	      <img class="media-object" src="../../assets/images/KOUSEI2.BMP" alt="...">
	    </a>
	    <div class="media-body">
	      <p class="media-heading">販売</p>
	    </div>
	  </li>

	  <li class="media">
	    <a class="pull-left">
	      <img class="media-object" src="../../assets/images/KOUSEI3.BMP" alt="...">
	    </a>
	    <div class="media-body">
	      <p class="media-heading">購買</p>
	    </div>
	  </li>

	  <li class="media">
	    <a class="pull-left">
	      <img class="media-object" src="../../assets/images/KOUSEI4.BMP" alt="...">
	    </a>
	    <div class="media-body">
	      <p class="media-heading">生産</p>
	    </div>
	  </li>

	  <li class="media">
	    <a class="pull-left">
	      <img class="media-object" src="../../assets/images/KOUSEI5.BMP" alt="...">
	    </a>
	    <div class="media-body">
	      <p class="media-heading">販売・購買</p>
	    </div>
	  </li>

	  <li class="media">
	    <a class="pull-left">
	      <img class="media-object" src="../../assets/images/KOUSEI6.BMP" alt="...">
	    </a>
	    <div class="media-body">
	      <p class="media-heading">販売・生産</p>
	    </div>
	  </li>

	  <li class="media">
	    <a class="pull-left">
	      <img class="media-object" src="../../assets/images/KOUSEI7.BMP" alt="...">
	    </a>
	    <div class="media-body">
	      <p class="media-heading">購買・生産</p>
	    </div>
	  </li>

	  <li class="media">
	    <a class="pull-left">
	      <img class="media-object" src="../../assets/images/KOUSEI0.BMP" alt="...">
	    </a>
	    <div class="media-body">
	      <p class="media-heading">販売・購買・生産</p>
	    </div>
	  </li>
</ul>

</div>

<div class="col-md-9">
<!-- <div class="btn-group"> -->
	<button type="button" class="btn btn-primary" onclick="$('#jstree').jstree('open_all');">　展　開　</button>
	<button type="button" class="btn btn-primary">　修　正　</button>
	<button type="button" class="btn btn-primary">　削　除　</button>
<!-- </div> -->

	<div style="margin-bottom: 10px"></div>
	<legend></legend>

	<%= render 'tree' %>
		
</div>

app/views/tree/_modal_form.html.erb
<%# Conditionally set remote: true. Also, passing model name as data attribute %>
<%= form_for(:person , html: {role: :form, 'data-model' => 'person'}) do |f| %>

    <%# Added Bootstrap classes, and help-block container for error messages %>
    <div class="form-group">
      <%= f.label :first_name, class: 'control-label' %><br>
      <%= f.text_field :first_name, class: 'form-control' %>
      <span class="help-block"></span>
    </div>

    <%# Added Bootstrap classes, and help-block container for error messages %>
    <div class="form-group">
      <%= f.label :last_name, class: 'control-label' %><br>
      <%= f.text_field :last_name, class: 'form-control' %>
      <span class="help-block"></span>
    </div>

    <%# Added Bootstrap classes %>
    <div class="actions">
      <%= f.submit 'Submit', class: 'btn btn-default' %>
    </div>

<% end %>

app/views/tree/_tree.html.erb
<div id="jstree">
		<ul>
		<% @records.each do |model|
			if model['レベル'] == '1'
				case model['品目区分']
				when '1'
					icon = '{"icon":"../../assets/images/KOUSEI1.BMP"}'
				when '2'
					icon = '{"icon":"../../assets/images/KOUSEI2.BMP"}'
				when '3'
					icon = '{"icon":"../../assets/images/KOUSEI3.BMP"}'
				when '4'
					icon = '{"icon":"../../assets/images/KOUSEI4.BMP"}'
				when '5'
					icon = '{"icon":"../../assets/images/KOUSEI5.BMP"}'
				when '6'
					icon = '{"icon":"../../assets/images/KOUSEI6.BMP"}'
				when '7'
					icon = '{"icon":"../../assets/images/KOUSEI7.BMP"}'
				when '8'
					icon = '{"icon":"../../assets/images/KOUSEI8.BMP"}'
				when '9'
					icon = '{"icon":"../../assets/images/KOUSEI9.BMP"}'
				end
		 %>
	    <li data-jstree = <%= icon %> id=<%= model['ツリー順序'] %>><%= model['表示ラベル'] %>
    <% end  
    end 
    %>
		
		<% @records.each do |model|
			if model['レベル'] == '2'
				case model['品目区分']
				when '1'
					icon = '{"icon":"../../assets/images/KOUSEI1.BMP"}'
				when '2'
					icon = '{"icon":"../../assets/images/KOUSEI2.BMP"}'
				when '3'
					icon = '{"icon":"../../assets/images/KOUSEI3.BMP"}'
				when '4'
					icon = '{"icon":"../../assets/images/KOUSEI4.BMP"}'
				when '5'
					icon = '{"icon":"../../assets/images/KOUSEI5.BMP"}'
				when '6'
					icon = '{"icon":"../../assets/images/KOUSEI6.BMP"}'
				when '7'
					icon = '{"icon":"../../assets/images/KOUSEI7.BMP"}'
				when '8'
					icon = '{"icon":"../../assets/images/KOUSEI8.BMP"}'
				when '9'
					icon = '{"icon":"../../assets/images/KOUSEI9.BMP"}'
				end
		 %>
	      <ul>
					<li data-jstree = <%= icon %> id=<%= model['ツリー順序'] %>><%= model['表示ラベル'] %></li>
	      </ul>
	      
	    <% end  
		    end 
	    %>
	      </li>
	    <!-- <li id="root_node_2">Root node 2</li> -->
	  </ul>
</div>

app/views/tree/email.html.erb
<%= javascript_include_tag "tree" %>

<ol class="breadcrumb">
  <li><%= link_to 'メニュー', main_path %></li>
  <!-- <li><a href="#">基準情報</a></li> -->
  <!-- <li><a href="#">セキュリティ管理</a></li> -->
  <li class="active">Email</li>
</ol>

<h2>メール存在をチェック	</h2>
<%= form_for @user, url: email_path, html:{class: 'form-horizontal'}, remote: true, method: :POST do |f| %>
<div class="form-group">
  <div class="col-sm-3">
	  <%= f.text_field :email, class: 'form-control' %>
	  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %> エラーが発生しました:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
	  <% end %>
		<span class = "error_explanation"><%= flash[:notice]  %></span>
  </div>
  <%= f.submit '🔎', class: 'btn btn-default' %>
</div>
<% end %>

<%= form_tag "/search", method: "get" do %>
  <%= label_tag :q, "Search for:" %>
  <%= text_field_tag :q, class: 'form-control' %>
  <%= submit_tag "Search" %>
<% end %>

app/views/tree/email.js.erb
  // $('span').text("Someone already has that username. Try another?");
 $('span').text("<%= flash[:notice] %>");

app/views/tree/index.html.erb
<%= javascript_include_tag 'tree' %>

<ol class="breadcrumb">
  <li><%= link_to 'メニュー', main_path %></li>
  <!-- <li><a href="#">基準情報</a></li> -->
  <!-- <li><a href="#">セキュリティ管理</a></li> -->
  <li class="active">Tree</li>

</ol>

<form class="form-horizontal" action="index" method="post" role="form">
<%= render 'header' %>
<%= render 'main' %>
</form>

app/views/tree/multiselect.erb
<%= javascript_include_tag 'tree' %>
<ol class="breadcrumb">
  <li><%= link_to 'メニュー', main_path %></li>
  <!-- <li><a href="#">基準情報</a></li> -->
  <!-- <li><a href="#">セキュリティ管理</a></li> -->
  <li class="active">Multiselect</li>
</ol>

<h1>マルティセレクト（複数選択）</h1>
<%= form_for @employer, url: employer_path, html:{'data-model' => 'employer'}, remote: true do |f| %>
<div class="col-md-3 col-md-offset-2"> </div>
<div class="btn-group" role="group" aria-label="...">
  <button id="add_new_employer" type="button" class="btn btn-default">　
  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>　
  </button>
  <button type="submit" class="btn btn-default" name="multidelete">　
    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>　
  </button>
</div>


<table id="multiselect_table" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
  <thead>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Position</th>
    <th>Office</th>
    <th>Age</th>
    <th>Start date</th>
    <th>Salary</th>
  </tr>
  </thead>

  <tfoot>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Position</th>
    <th>Office</th>
    <th>Age</th>
    <th>Start date</th>
    <th>Salary</th>
  </tr>
  </tfoot>

  <tbody>
  <% @employers.each do |employwer| %>
  <tr>
    <th><%= check_box_tag "delete[#{employwer.id}]", 1 %></th>
    <td><a href="" > <%= employwer.first_name %></a></td>
    <td><%= employwer.position %></td>
    <td><%= employwer.office %></td>
    <td><%= employwer.age %></td>
    <td><%= employwer.start_date %></td>
    <td><%= employwer.salary %></td>
  </tr>
  <% end %>
  </tbody>
</table>


<%# link_to 'New Person', '#new_person_modal', 'data-toggle' => 'modal' %>

<%# Bootstrap modal markup. @see: http://getbootstrap.com/javascript/#modals %>
<div class="modal fade" id="new_employer_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">追加情報入力</h4>
      </div>
      <div class="modal-body">
        <%# Render the new person form (passing modal => true to enable remote => true) %>
         <%# render 'modal_form' %>
        <%# Added Bootstrap classes, and help-block container for error messages %>
        <div class="form-group">
          <%= f.label :お名前, class: 'control-label' %><br>
          <%= f.text_field :first_name, class: 'form-control' %>
          <span class="help-block"></span>
        </div>

        <%# Added Bootstrap classes, and help-block container for error messages %>
        <div class="form-group">
          <%= f.label :位置, class: 'control-label' %><br>
          <%= f.text_field :position, class: 'form-control' %>
          <span class="help-block"></span>
        </div>

        <%# Added Bootstrap classes, and help-block container for error messages %>
        <div class="form-group">
          <%= f.label :オフィス, class: 'control-label' %><br>
          <%= f.text_field :office, class: 'form-control' %>
          <span class="help-block"></span>
        </div>

        <%# Added Bootstrap classes, and help-block container for error messages %>
        <div class="form-group">
          <%= f.label :年齢, class: 'control-label' %><br>
          <%= f.text_field :age, class: 'form-control' %>
          <span class="help-block"></span>
        </div>

        <%# Added Bootstrap classes, and help-block container for error messages %>
        <div class="form-group">
          <%= f.label :開始日, class: 'control-label' %><br>
          <%= f.text_field :start_date, class: 'form-control' %>
          <span class="help-block"></span>
        </div>

        <%# Added Bootstrap classes, and help-block container for error messages %>
        <div class="form-group">
          <%= f.label :給料, class: 'control-label' %><br>
          <%= f.text_field :salary, class: 'form-control' %>
          <span class="help-block"></span>
        </div>

        <%# Added Bootstrap classes %>
        <div class="actions">
          <%= f.submit '追加', class: 'btn btn-default', name: 'add' %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

<% end %>

app/views/tree/upload.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'メニュー', main_path %></li>
  <!-- <li><a href="#">基準情報</a></li> -->
  <!-- <li><a href="#">セキュリティ管理</a></li> -->
  <li class="active">Upload</li>
</ol>

<h2>ファイルをアップロード	</h2>
<span><%= notice %></span>
<%= form_for :person, url: uploadFile_path, html:{class: 'form-horizontal'} do |f| %>
<div class="form-group">
  <div class="col-sm-3">
	  <%= f.file_field :picture, class: 'form-control' %>
  </div>
  <%= f.submit 'Upload', class: 'btn btn-primary' %>
</div>
<% end %>